"""集中定义 PDF raster 与 layout contract 中不可随意漂移的常量。"""

PDF_RASTER_SCALE = 2.0
PDF_RASTER_DPI = 144
PDF_INVISIBLE_TEXT_RENDER_MODES = frozenset({3, 7})
PDF_SCAN_IMAGE_COVERAGE_THRESHOLD = 0.5
PP_DOCLAYOUT_V3_INPUT_SIZE = 800
PP_DOCLAYOUT_V3_SCORE_THRESHOLD = 0.5
